---
language: python
services: docker
env:
  global:
    - ROLE_NAME: mysql
before_install:
  - sudo apt-get -qq update
install:
  - python3 -m pip install "ansible<2.10"
  - python3 -m pip install molecule[docker,lint]
before_script:
  - cd ../
  - mv ansible-role-$ROLE_NAME $ROLE_NAME
  - cd $ROLE_NAME
script:
  - molecule test
notifications:
  email: false
  # slack:
  #   secure: 'execute `travis encrypt "<slack_name>:<token>" --add notifications.slack -x --no-interactive`'
